print("Docs: https://docs.python.org/3.7/tutorial/datastructures.html#using-lists-as-stacks")
my_list = [1,2,3,4,5]
print("Return the list: ", my_list)
print("Return every second item: ", my_list[::2])
print("Return reverse: ", my_list[::-1])
print("Return length: ", len(my_list))
print("Return last item: ", my_list[len(my_list) - 1])
my_list[0:2] = []
print("Removed slice from 0 to 2 (not including): ", my_list)
my_list.remove(4)
print("Removed item with value 4: ", my_list)
print("Get last item from the list and remove it: ", my_list.pop())
my_list.insert(0, 2)
print("Added value 2 at the start of the list: ", my_list)
print("Now let's add a bit more of data")
my_list.insert(0, 2)
my_list.insert(1, 1)
print("Result: ", my_list)
my_list.remove(2)
print("Removed item with value 2: ", my_list)
my_list.remove(2)
print("Removed item with value 2 once again: ", my_list)
